### ISSUE TITLE
Move `txOutRefAtState` and other Tx utils to Atlas

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/clb#16]
No objections, will move it out to Atlas.

_Originally posted by @euonymos in https://github.com/mlabs-haskell/clb/pull/15#discussion_r1520810599_

**Comment by uhbif19** [comment]
@euonymos Now there is no CLB PR/code in Atlas to change? Or is it here https://github.com/mlabs-haskell/atlas/pull/1 ?

**Comment by euonymos** [comment]
Done.
