### ISSUE TITLE
Output Datums are not indexed

### ISSUE THREAD

**Issue by mikekeke** [mlabs-haskell/clb#45]
I'm using `CLB` through integration in `Atlas` and during unit testing bumped into an issue when Datums can not be found by hash after transaction is submitted. `mockDatums` Map remains empty through the whole test run.

I've copy-pasted [scriptDataFromCardanoTxBody](https://github.com/mlabs-haskell/clb/blob/76a48110fe3796acc9f9151477c7f5ab24162216/src/Clb.hs#L400-L416) to my project to see what is going on there, and seems like getting Datums only from `(L.TxDats' dats)` is not enough, as in my case it's an empty map. But I can see that Datums are present in transaction outputs as they suppose to. Probably, Datums can be extracted from outputs as well for proper indexing.

UPD: I'm submitting transactions with inline datums.

**Comment by mikekeke** [comment]
Hmm, I just noticed [this comment](https://github.com/mlabs-haskell/clb/blob/76a48110fe3796acc9f9151477c7f5ab24162216/src/Clb.hs#L160C5-L160C21). Does that mean that inline datums are not supposed to be saved to `mockDatums `?

**Comment by euonymos** [comment]
I guess I wrongly decided we didn't want to hash them, but it looks as if we should do it.

**Comment by euonymos** [comment]
@mikekeke So I got a moment to fix that and the comment was misleading. [scriptDataFromCardanoTxBody](https://github.com/mlabs-haskell/clb/blob/76a48110fe3796acc9f9151477c7f5ab24162216/src/Clb.hs#L400-L416) in reality takes datums which are tx witness (when we spend an output) and you want inline datums to be indexed upon creating an output. Is that correct? Do you think it makes sense to store all of them in one place or have separate maps for existing datums and those known from witnesses?

**Comment by mikekeke** [comment]
@euonymos 
> and you want inline datums to be indexed upon creating an output. Is that correct?

Yeah. At least that what I was expecting: after transaction that adds datum on chain is submitted, I would expect that there is some straightforward way to lookup this datum. If I understand correctly, it should be possible to look them up in `EmulatedLedgerState`, but providing indexed datums can help a lot I think.

> Do you think it makes sense to store all of them in one place or have separate maps for existing datums and those known from witnesses?

Hmm, tricky question. Storing them in one place can probably automatically fix Atlas's `lookupDatum`, [as it uses `mockDatums`](https://github.com/geniusyield/atlas/blob/abc35aff8119310d030db754000a70854ca5f0a2/src/GeniusYield/Test/Clb.hs#L273C17-L273C27). But storing them in separate places can be handy for debugging with CLB.

Maybe CLB can export its own `lookupDatum`, or this is not CLB's responsibility?

**Comment by euonymos** [comment]
Meanwhile, I added all datums into the cache: https://github.com/mlabs-haskell/clb/commit/5175dd5120968327b2df9fda96f051d429e4cfef

It was merged into `master`.

`lookupDatum` currently is a part of Atlas I think, but if it's needed we can provide additional API to work with output datums and witness datums separately in the future, let me close the issue for now.
