### ISSUE TITLE
Export more modules

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/clb#6]
CLB clients do require at least `Clb.ClbLedgerState` and `Clb.MockConfig` for getting emulator params. Probably also `Clb.TimeSlot`.

**Comment by euonymos** [comment]
For the time being, I exported everything that was needed for Atlas (in the corresponding branch, but I will pick up those changes in the branch for CEM Script).

**Comment by uhbif19** [comment]
I do not understand. Was not initial versions pinned for Atlas?
