### ISSUE TITLE
Support for stacking

### ISSUE THREAD

**Issue by uhbif19** [mlabs-haskell/clb#7]
This is similar to slotting. Real consensus has slots moving, and our emulator should have slot changing API instead.

Same goes for stacking rewards. We should probably have simple API for selection of slotting leader, not really conforming PoS algorithm.

We could use PoS docs to check it working correctly.

**Comment by euonymos** [comment]
You are quite right, the ledger is capable of handling the state of certificates (from what I saw) and probably something else. We have to use this. In terms of emulating, I would say we need to emulate a set of SPOs that can used to delegate funds (and related things) @uhbif19 .

**Comment by euonymos** [comment]
I have some doubts about how we should do that, but the bottom line is to try to reuse the ledger as far as possible.
